version: '3'

services:
  django:
    container_name: law-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=law.samaranin.dev,www.law.samaranin.dev
      - LETSENCRYPT_HOST=law.samaranin.dev
      - LETSENCRYPT_EMAIL=admin@law.samaranin.dev
      - VIRTUAL_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - "./:/app"
    expose:
      - 8000
    command: python /app/manage.py runserver 0.0.0.0:8000

networks:
  nginx-proxy:
    external: true