# Generated by Django 3.2.15 on 2022-10-12 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameStatusCase', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameTypeCase', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Baza_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=100, verbose_name='ПІБ клієнта')),
                ('contract_number', models.IntegerField(verbose_name='Номер договору')),
                ('date_contract', models.DateField(verbose_name='Дата договору')),
                ('date', models.DateField(verbose_name='Дата подачі справи')),
                ('documents_case', models.FileField(upload_to='DownloadFile/%Y/%m/%d/', verbose_name='Загрузка документів')),
                ('status_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.statuscase')),
                ('type_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.typecase')),
            ],
        ),
    ]
