# Generated by Django 3.2.15 on 2022-10-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baza_client',
            name='documents_case',
        ),
    ]
