# Generated by Django 4.2.6 on 2023-10-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_baza_client_documents_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baza_client',
            name='documents_case',
            field=models.FileField(blank=True, null=True, upload_to='DownloadFile/%Y/%m/%d/', verbose_name='Загрузка документів'),
        ),
    ]
